# Semana 3 – Introducción a Python para manejo de datos científicos

## Modelamiento computacional de procesos geoquímicos

En esta sesión introducimos el uso de **Python** como herramienta para el manejo y análisis
de datos científicos, con énfasis en aplicaciones geoquímicas y ambientales.

## Objetivos de la sesión

Al finalizar esta sesión, el estudiante será capaz de:

- Entender qué es Python y por qué se usa en ciencias de la Tierra
- Utilizar Python como calculadora científica
- Definir variables y trabajar con listas
- Manipular datos numéricos con NumPy
- Trabajar con datos tabulares usando pandas
- Leer y escribir archivos CSV


## 1. ¿Qué es Python y por qué usarlo en geoquímica?

Python es un lenguaje de programación ampliamente utilizado en:

- Análisis de datos geoquímicos
- Procesamiento de resultados de modelos (PHREEQC, simulaciones)
- Datos de sensores ambientales
- Visualización científica

En este curso, Python se usará como una **herramienta para analizar datos**, no como
programación avanzada.

## 2. Variables en Python

## ¿Qué es una variable?

Una **variable** es un nombre que se le asigna a un valor para poder usarlo
posteriormente en un programa.

En ciencias de la Tierra, una variable puede representar:
- temperatura
- profundidad
- tiempo
- velocidad
- pH
- presión
- identificadores de muestras o estaciones



In [7]:
temperature = 25.0

En este ejemplo, la variable `temperature` almacena un valor numérico que podría
representar una temperatura medida en grados Celsius.

## Reglas básicas para nombrar variables

En Python:

- Los nombres deben comenzar con una letra o con `_`
- No pueden contener espacios
- No deben usar caracteres especiales
- Son sensibles a mayúsculas y minúsculas (`temp` ≠ `Temp`)
- Es buena práctica usar nombres descriptivos

In [9]:
depth_m = 150
wind_speed_ms = 5.2
station_id = "ST-01"

Usar nombres claros facilita la lectura y comprensión del código,
especialmente en trabajos científicos.

## Tipos de variables (tipos de datos)

Python asigna automáticamente un **tipo de dato** a cada variable.
Los tipos más comunes son:

- `int`: números enteros
- `float`: números reales
- `str`: texto (cadenas de caracteres)

In [ ]:
year = 2025
rainfall_mm = 125.4
site_name = "Cuenca Norte"

In [ ]:
type(year), type(rainfall_mm), type(site_name)

## Operaciones con variables numéricas

Las variables numéricas pueden utilizarse en operaciones matemáticas
como sumas, restas, multiplicaciones y divisiones.

In [11]:
distance_km = 12.5
time_h = 0.5

velocity_kmh = distance_km / time_h
velocity_kmh

25.0

Este tipo de cálculo es común en muchas áreas de las Ciencias de la Tierra,
por ejemplo para estimar velocidades, tasas o flujos.

## Actualización del valor de una variable

El valor de una variable puede cambiar durante la ejecución del programa.

In [ ]:
sea_level = 1.20
sea_level

In [ ]:
sea_level = sea_level + 0.05
sea_level

Aquí estamos actualizando el valor de una variable, por ejemplo para simular
un cambio en el nivel del mar.

## Variables de texto (strings)

Las variables también pueden almacenar texto, lo cual es útil para:
- nombres de estaciones
- etiquetas
- mensajes informativos

In [14]:
station_name = "Estación Costera"
station_name

print("Datos registrados en la", station_name)

Datos registrados en la Estación Costera


## Buenas prácticas al usar variables

- Usar nombres descriptivos
- Incluir unidades cuando sea posible (`_m`, `_C`, `_ms`)
- Evitar nombres genéricos como `x`, `y`, `a`
- Pensar las variables como cantidades físicas reales

## Ejercicio 1

1. Defina variables para:
   - temperatura
   - profundidad
   - tiempo
2. Calcule una velocidad o tasa simple
3. Imprima un mensaje con los valores obtenidos

## 3. Python como calculadora cientifica

In [ ]:
2+3

In [ ]:
10/3

In [ ]:
(10/3)*100

## 4. Variables y operaciones básicas

In [ ]:
ca = 40.08   # masa atómica del calcio
mg = 24.31   # masa atómica del magnesio

ratio = ca / mg
ratio

Las variables permiten almacenar valores y reutilizarlos en cálculos posteriores.

## 5. Listas: conjuntos simples de datos

In [32]:
ph = [6.8, 7.1, 7.3, 6.9]
ph

[6.8, 7.1, 7.3, 6.9]

In [4]:
ph[0]
ph[3]

6.8

In [37]:
print(ph[0:3])

[6.8, 7.1, 7.3]


In [39]:
print(ph[:2])
print(ph[2:])

[6.8, 7.1]
[7.3, 6.9]


In [ ]:
Las listas pueden representar, por ejemplo, valores de pH medidos en diferentes muestras.

## 6. Arreglos numéricos con NumPy

NumPy permite realizar operaciones estadísticas de forma eficiente sobre conjuntos de datos.

In [29]:
import numpy as np

In [43]:
ph_array = np.array(ph)

print(ph_array)

ph_times10= ph_array*10

print(ph_times10)

[6.8 7.1 7.3 6.9]
[68. 71. 73. 69.]


In [31]:
ph_array.mean()

np.float64(7.025)

In [10]:
ph_array.min(), ph_array.max()

(np.float64(6.8), np.float64(7.3))

In [49]:
ph_list_of_lists = [ph_array,ph_times10]

print(ph_list_of_lists[0])

[6.8 7.1 7.3 6.9]


In [50]:
print(ph_list_of_lists[0][0])

print(ph_list_of_lists[1][0])

6.8
68.0


## 7. Manejo de datos tabulares con pandas

In [2]:
import pandas as pd

### 7.1 Creación de un DataFrame

In [18]:
data = {
    'Sample': ['A', 'B', 'C'],
    'pH': [7.1, 6.8, 7.4],
    'Ca_mgL': [45, 60, 30],
    'Mg_mgL': [12, 18, 10]
}

df = pd.DataFrame(data)
df

Sample   pH  Ca_mgL  Mg_mgL
0      A  7.1      45      12
1      B  6.8      60      18
2      C  7.4      30      10

Un **DataFrame** es similar a una hoja de Excel, pero permite automatizar cálculos.

### 7.2 Operaciones con columnas

In [14]:
df['Ca_Mg_ratio'] = df['Ca_mgL'] / df['Mg_mgL']
df

Sample   pH  Ca_mgL  Mg_mgL  Ca_Mg_ratio
0      A  7.1      45      12     3.750000
1      B  6.8      60      18     3.333333
2      C  7.4      30      10     3.000000

### 7.3 Filtrado de datos

In [15]:
df[df['pH'] > 7.0]

Sample   pH  Ca_mgL  Mg_mgL  Ca_Mg_ratio
0      A  7.1      45      12         3.75
2      C  7.4      30      10         3.00

### 7.4 Estadísticas básicas

In [17]:
df.describe()

pH  Ca_mgL     Mg_mgL  Ca_Mg_ratio
count  3.00     3.0   3.000000     3.000000
mean   7.10    45.0  13.333333     3.361111
std    0.30    15.0   4.163332     0.375771
min    6.80    30.0  10.000000     3.000000
25%    6.95    37.5  11.000000     3.166667
50%    7.10    45.0  12.000000     3.333333
75%    7.25    52.5  15.000000     3.541667
max    7.40    60.0  18.000000     3.750000

## 8. Lectura de datos desde un archivo CSV

Supongamos que tenemos un archivo llamado `water_samples.csv` que contiene informacion de una campaña donde se han realizado analisis a varias pozos de agua subterranea. Nuestra mision es poder colocar todos estos datos en un DataFrame para luego usarlos en nuestro analisis.

In [17]:
df_csv = pd.read_csv('./water_samples.csv')
df_csv.head(10)

Sample   pH  Temperature_C  EC_uScm  Ca_mgL  Mg_mgL  Na_mgL  K_mgL  \
0     A1  6.8           24.5      420      38      12      22    3.1   
1     A2  7.1           25.0      510      45      15      28    3.6   
2     A3  7.4           26.2      620      52      18      35    4.2   
3     A4  6.6           23.9      395      32      11      20    2.9   
4     A5  7.0           24.8      480      40      14      25    3.4   
5     B1  6.5           23.8      390      30      10      18    2.8   
6     B2  6.9           24.1      450      36      13      24    3.2   
7     B3  7.2           25.5      580      48      17      32    3.9   
8     B4  7.5           26.0      660      55      19      38    4.5   
9     B5  6.7           24.2      410      34      12      21    3.0   

   HCO3_mgL  SO4_mgL  Cl_mgL  
0       145       18      25  
1       170       22      30  
2       190       30      42  
3       130       16      22  
4       160       21      28  
5       120       15      20  
6       150       20      27  
7       180       28      38  
8       200       33      46  
9       140       17      24

Información básica del conjunto de datos:

In [5]:
df_csv.columns

Index(['Sample', 'pH', 'Temperature_C', 'EC_uScm', 'Ca_mgL', 'Mg_mgL',
       'Na_mgL', 'K_mgL', 'HCO3_mgL', 'SO4_mgL', 'Cl_mgL'],
      dtype='object')

In [6]:
df_csv.shape

(20, 11)

## 9. Guardar resultados en un nuevo archivo CSV

In [20]:
df.to_csv('processed_water_data.csv', index=False)

Aqui puedes encontrar mas informacion sobre fundamentos basicos de python aplicado a las Ciencias de la Tierra

https://earthdatascience.org/courses/intro-to-earth-data-science/python-code-fundamentals/

https://www.learnpython.org

## 10. EJERCICIOS

## Ejercicio 1 – Crear listas a partir de datos

Los datos de la tabla a continuación representan la **precipitación media mensual**
(en pulgadas) para una estación meteorológica.

Estos datos son similares a los que se usan comúnmente en climatología,
hidrología y ciencias ambientales.

### Datos disponibles

| Mes | Precipitación (pulgadas) |
|----|--------------------------|
| jan | 0.70 |
| feb | 0.75 |
| mar | 1.85 |
| apr | 2.93 |
| may | 3.05 |
| jun | 2.02 |
| jul | 1.93 |
| aug | 1.62 |
| sept | 1.84 |
| oct | 1.31 |
| nov | 1.39 |
| dec | 0.84 |

### Instrucciones

1. Crea una lista de Python que contenga las abreviaturas de los meses.
   - La lista debe llamarse `precip_months`

2. Crea una segunda lista que contenga los valores de precipitación.
   - La lista debe llamarse `precip_inches`

⚠️ **Importante**:
- Los meses deben ser cadenas de texto (`str`)
- Los valores de precipitación deben ser números reales (`float`)
- Los datos deben estar **en el mismo orden** que aparecen en la tabla

## Ejercicio 2 – Conversión de unidades en una lista

En este ejercicio trabajarás con una lista ya existente y modificarás sus valores
para convertir unidades, una tarea muy común en las Ciencias de la Tierra.

### Contexto

Dispones de una lista llamada `precip_inches` que contiene valores de precipitación
mensual en **pulgadas**.

Tu objetivo es convertir estos valores a **milímetros (mm)** y almacenar el resultado
en una **nueva lista**, sin modificar la lista original.
    

### Instrucciones

1. Crea una variable llamada `inch_to_mm` con el valor de conversión:
   
   - 1 pulgada = 25.4 mm

2. Crea una copia de la lista `precip_inches` y asígnala a una nueva variable
   llamada `precip_mm`

3. Convierte cada valor de la lista `precip_mm` de pulgadas a milímetros
   multiplicando por el factor de conversión

💡 **Pista**:
- Puedes usar indexación (`lista[i]`)
- O cualquier método que conozcas para recorrer una lista


## Ejercicio 3 – Crear una lista de listas

En este ejercicio aprenderás a crear una **lista de listas**, es decir,
una estructura de datos que contiene varias listas en su interior.

Este tipo de estructura es útil para organizar datos relacionados antes
de pasarlos a estructuras más avanzadas como arreglos de NumPy o DataFrames.

### Contexto

Dispones de las siguientes listas creadas en los ejercicios anteriores:

- `precip_months` → lista con los meses
- `precip_mm` → lista con valores de precipitación en milímetros

Tu objetivo es agrupar estas listas en una sola estructura.

### Instrucciones

1. Crea una nueva lista llamada `all_precip_data`
2. Esta lista debe contener:
   - `precip_months` como la primera sublista
   - `precip_mm` como la segunda sublista

💡 **Pista**:
Una lista de listas se puede crear usando la siguiente sintaxis:

```python
lista_de_listas = [lista_1, lista_2]

### Verificación

Imprime la variable `all_precip_data` y verifica que:

- Contiene dos sublistas
- El orden de los datos es correcto

### Preguntas de reflexión (no requieren código)

- ¿Qué ventajas tiene agrupar datos relacionados en una sola estructura?
- ¿Qué limitaciones tiene una lista de listas frente a una tabla?

## Ejercicio 4 – Graficar datos desde una lista de listas

En este ejercicio crearás una gráfica a partir de una **lista de listas**
utilizando la librería `matplotlib`.

El objetivo es practicar:
- indexación correcta de listas anidadas
- creación de gráficos básicos
- personalización de títulos y ejes

### Contexto

Dispones de una lista llamada `all_precip_data` con la siguiente estructura:

- `all_precip_data[0]` → meses
- `all_precip_data[1]` → precipitación mensual (mm)

Tu objetivo es usar esta estructura para crear una gráfica de barras.

### Instrucciones

Modifica el código a continuación para:

1. Usar correctamente los datos contenidos en `all_precip_data`
2. Cambiar el color de la gráfica a un tono azul (por ejemplo `"aqua"`)
3. Agregar un título descriptivo
4. Etiquetar correctamente los ejes (incluyendo unidades)
5. Ajustar el tamaño de la figura

In [ ]:
# Importar la librería necesaria
import matplotlib.pyplot as plt

# Crear figura y ejes
fig, ax = plt.subplots(figsize=(6, 6))

# Graficar datos (modifica estas líneas)
ax.bar(
    listname_x_axis,
    listname_y_axis,
    color="red"
)

# Configurar títulos y etiquetas
ax.set(
    title="Add plot title here",
    xlabel="Add x axis label here",
    ylabel="Add y axis label here"
)

plt.show()

### Preguntas de reflexión (no requieren código)

- ¿Por qué es importante saber cómo están organizados los datos antes de graficar?
- ¿Qué limitaciones tiene trabajar con listas frente a usar un DataFrame?